language: ruby
bundler_args: --without copyright
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-1.7.27
  - jruby-9.1.2.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.2.0
